 
 -------------- celery@hp v5.3.1 (emerald-rush)
--- ***** ----- 
-- ******* ---- Linux-6.2.0-33-generic-x86_64-with-glibc2.35 2023-10-10 13:02:13
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         config:0x7fd3f34d6e30
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . api.v1.accounts.tasks.create_objects_for_student
  . api.v1.authentications.tasks.send_confirm_link_email
  . api.v1.authentications.tasks.send_password_reset_email
  . api.v1.lessons.tasks.change_student_lesson_view_statistics
  . api.v1.payments.tasks.change_student_tariff_expire_date
  . api.v1.questions.tasks.update_student_wrong_answers
  . config.celery.debug_task

[2023-10-10 13:02:13,729: WARNING/MainProcess] /home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:498: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-10-10 13:02:13,871: INFO/MainProcess] Connected to redis://localhost:6379/0
[2023-10-10 13:02:13,872: WARNING/MainProcess] /home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:498: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-10-10 13:02:13,873: INFO/MainProcess] mingle: searching for neighbors
[2023-10-10 13:02:14,880: INFO/MainProcess] mingle: all alone
[2023-10-10 13:02:14,904: INFO/MainProcess] celery@hp ready.

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
 
 -------------- celery@hp v5.3.1 (emerald-rush)
--- ***** ----- 
-- ******* ---- Linux-6.2.0-33-generic-x86_64-with-glibc2.35 2023-10-10 13:02:51
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         config:0x7f0ac9fdee30
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . api.v1.accounts.tasks.create_objects_for_student
  . api.v1.authentications.tasks.send_confirm_link_email
  . api.v1.authentications.tasks.send_password_reset_email
  . api.v1.lessons.tasks.change_student_lesson_view_statistics
  . api.v1.payments.tasks.change_student_tariff_expire_date
  . api.v1.questions.tasks.update_student_wrong_answers
  . config.celery.debug_task

[2023-10-10 13:02:52,148: WARNING/MainProcess] /home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:498: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-10-10 13:02:52,154: INFO/MainProcess] Connected to redis://localhost:6379/0
[2023-10-10 13:02:52,155: WARNING/MainProcess] /home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:498: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-10-10 13:02:52,158: INFO/MainProcess] mingle: searching for neighbors
[2023-10-10 13:02:53,170: INFO/MainProcess] mingle: all alone
[2023-10-10 13:02:53,193: INFO/MainProcess] celery@hp ready.
 
 -------------- celery@hp v5.3.1 (emerald-rush)
--- ***** ----- 
-- ******* ---- Linux-6.2.0-33-generic-x86_64-with-glibc2.35 2023-10-10 13:02:57
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         config:0x7f3bbbfbee30
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . api.v1.accounts.tasks.create_objects_for_student
  . api.v1.authentications.tasks.send_confirm_link_email
  . api.v1.authentications.tasks.send_password_reset_email
  . api.v1.lessons.tasks.change_student_lesson_view_statistics
  . api.v1.payments.tasks.change_student_tariff_expire_date
  . api.v1.questions.tasks.update_student_wrong_answers
  . config.celery.debug_task

[2023-10-10 13:02:57,523: WARNING/MainProcess] /home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:498: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-10-10 13:02:57,527: INFO/MainProcess] Connected to redis://localhost:6379/0
[2023-10-10 13:02:57,528: WARNING/MainProcess] /home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:498: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-10-10 13:02:57,531: INFO/MainProcess] mingle: searching for neighbors

worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
[2023-10-10 13:02:58,542: INFO/MainProcess] mingle: all alone
[2023-10-10 13:02:58,567: INFO/MainProcess] celery@hp ready.
[2023-10-10 15:59:32,650: INFO/MainProcess] Task api.v1.lessons.tasks.change_student_lesson_view_statistics[0a4f6345-a25a-4050-a37a-05dc30f7c6f8] received
[2023-10-10 15:59:32,665: INFO/ForkPoolWorker-7] Task api.v1.lessons.tasks.change_student_lesson_view_statistics[0a4f6345-a25a-4050-a37a-05dc30f7c6f8] succeeded in 0.013381484001001809s: None
[2023-10-10 16:48:51,438: INFO/MainProcess] Task api.v1.lessons.tasks.change_student_lesson_view_statistics[fd27ebd3-ee71-4ac2-8ff6-958f4a434806] received
[2023-10-10 16:48:51,445: INFO/ForkPoolWorker-7] Task api.v1.lessons.tasks.change_student_lesson_view_statistics[fd27ebd3-ee71-4ac2-8ff6-958f4a434806] succeeded in 0.006385688000591472s: None

Restarting celery worker (/home/oybek/projects/korkort_deploy/venv/bin/celery -A config worker -l info)
 
 -------------- celery@hp v5.3.1 (emerald-rush)
--- ***** ----- 
-- ******* ---- Linux-6.2.0-33-generic-x86_64-with-glibc2.35 2023-10-10 16:51:50
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         config:0x7f38e1dfcd60
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . api.v1.accounts.tasks.create_objects_for_student
  . api.v1.authentications.tasks.send_confirm_link_email
  . api.v1.authentications.tasks.send_password_reset_email
  . api.v1.lessons.tasks.change_student_lesson_view_statistics
  . api.v1.payments.tasks.change_student_tariff_expire_date
  . api.v1.questions.tasks.update_student_wrong_answers
  . config.celery.debug_task

[2023-10-10 16:51:51,261: WARNING/MainProcess] /home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:498: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-10-10 16:51:51,268: INFO/MainProcess] Connected to redis://localhost:6379/0
[2023-10-10 16:51:51,269: WARNING/MainProcess] /home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:498: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-10-10 16:51:51,271: INFO/MainProcess] mingle: searching for neighbors
[2023-10-10 16:51:52,286: INFO/MainProcess] mingle: all alone
[2023-10-10 16:51:52,303: INFO/MainProcess] celery@hp ready.
[2023-10-10 16:51:59,375: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 336, in start
    blueprint.start(self)
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 726, in start
    c.loop(*c.loop_args())
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 373, in create_loop
    cb(*cbargs)
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/kombu/transport/redis.py", line 1341, in on_readable
    self.cycle.on_readable(fileno)
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/kombu/transport/redis.py", line 566, in on_readable
    chan.handlers[type]()
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/kombu/transport/redis.py", line 910, in _receive
    ret.append(self._receive_one(c))
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/kombu/transport/redis.py", line 920, in _receive_one
    response = c.parse_response()
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/redis/client.py", line 1542, in parse_response
    response = self._execute(conn, try_read)
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/redis/client.py", line 1518, in _execute
    return conn.retry.call_with_retry(
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/redis/client.py", line 1520, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    raise error
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/redis/client.py", line 1540, in try_read
    return conn.read_response(disconnect_on_error=False)
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/redis/connection.py", line 882, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/redis/connection.py", line 349, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/redis/connection.py", line 359, in _read_response
    raw = self._buffer.readline()
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/redis/connection.py", line 262, in readline
    self._read_from_socket()
  File "/home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/redis/connection.py", line 215, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2023-10-10 16:51:59,379: WARNING/MainProcess] /home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:386: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered
back to the queue. You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss
setting. In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2023-10-10 16:51:59,382: WARNING/MainProcess] /home/oybek/projects/korkort_deploy/venv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:498: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-10-10 16:51:59,383: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

